--- #Install Jenkins and deployment tools on EC2

- hosts: all
  become: yes
  roles:
    - role: geerlingguy.mysql
      mysql_databases:
        - name: gogs
          encoding: latin1
          collation: latin1_general_ci
      mysql_users:
        - name: gogs
          host: "%"
          password: gogs
          priv: "gogs.*:ALL"
    - role: geerlingguy.gogs
