--- #Install Jenkins and deployment tools on EC2

- hosts: all
  become: yes
  roles:
    - role: geerlingguy.ansible-role-packer
    - role: geerlingguy.docker
    - role: geerlingguy.ansible
    - role: geerlingguy.jenkins
      jenkins_plugins:
        - git
        - github
        - jenkins-multijob-plugin
        - pipeline-stage-view
        - github-organization-folder
        - copyartifact
        - workflow-aggregator
        - dashboard-view
